### PR TITLE
Fix to connect, add disquss and fix tags card

### PR DESCRIPTION
**Pull request by sielay**
* Add disquss #2
 * Fix anchor issue #47 
 * Fix connect that breaks after refreshing dependencies

### CODE REVIEW

**Comment by sielay** [comment]
The issue can be solved by change in `tsconfig` but I want to drill it down as it repeats for everyone and basically blocks `build` task.

**Comment by fabien0102** [comment]
Deploy preview for *fabien0102-gatsby-starter* ready!

Built with commit 5f59b47a0f19f6d97e8672f00cc960e3342664ef

https://deploy-preview-53--fabien0102-gatsby-starter.netlify.com

**Comment by sielay** [comment]
Will rebase it in the evening

**Comment by fabien0102** [comment]
@sielay You can merge this PR after your rebase if everything is green 😉 You are now a collaborator of this project 🎉

**Comment by sielay** [comment]
@fabien0102 any reason you prefer merge over squash & merge?

**Comment by fabien0102** [comment]
@sielay I just like to have a real history :wink: It's better for debugging, understand the context, git bisect, …

**Comment by sielay** [comment]
Ok. @fabien0102 That's the only reason I did not merge. In my projects, I like to have a simple chart as it's easier to read. I don't see a difference between those two: And seeing people experimenting while patching just distracts me ;)

```
Mege                           Sqash and merge

 |                                      |
 M                                      C'
 |\                                     |
 |  \                                   |
 |   C                                  |   C
 |   |                                  |   |
 |   C                                  |   C
 |  /                                   |  /
 |/                                     |/ 
 P                                      P
```

**Pull request merged**
