### PR TITLE
Housekeeping - updates & fixes

### PR DESCRIPTION
**Pull request by jamestharpe**
- Fixes spelling of "programmatically"
- Replaces "precommit" npm script with "husky" config to remove warning
- Multiple package version upgrades to resolve security warnings and issues running on Windows
- Add "remark-frontmatter" dependency to resolve build error

### CODE REVIEW

**Comment by jamestharpe** [comment]
Hi @fabien0102 - just wanted to say THANK YOU for putting this starter together, I really like it! 

I had some trouble getting up-and-running, but everything is now looking good and this pull request resolves all the issues I had. I hope you find it useful!

**Comment by jamestharpe** [comment]
Not sure why `deploy/netlify` failed - the log shows no errors. Maybe it timed out? LMK if I can troubleshoot somehow.

**Comment by fabien0102** [comment]
Let's try to retry the build, no obvious errors indeed (at least from now ^^)

**Comment by fabien0102** [comment]
image

Some unused variables 😬  Normally the logs are public, @jamestharpe tell me if not so I will paste the beast here ^^

(sorry by advance if I'm not very reactive, it's totally the rush at my job 😅)

**Comment by jamestharpe** [comment]
I fixed what I could glean from the logs, but it's failing w/ out error again :-\

Can you tell me what command is failing and I'll take care of it locally?

**Comment by fabien0102** [comment]
Let's try to re-build… 😕

**Comment by fabien0102** [comment]
ok… I will try to build locally to see

**Comment by fabien0102** [comment]
of course, everything works locally… 🤔

**Comment by fabien0102** [comment]
Let's retry with npm instead of yarn, maybe, I hate when netlify crash like this!

**Comment by fabien0102** [comment]
image

YES! I may have something, try to run `yarn storybook:build`, it's failing locally and netlify also built it

**Comment by jamestharpe** [comment]
Ah, okay - hadn't tested that command! I don't know much about storybook, but I'll see what I can do.

**Comment by jamestharpe** [comment]
I think I fixed it after going down a bit of a rabbit hole (we'll see when the build finishes!). `storybook` wasn't compatible with version of TypeScript that was being installed, so I updated TypeScript which required `storybook` to be recompiled. I ended up needing to run `npm install -g --production windows-build-tools` then `npn rebuild` to recompile `storybook`, at which point the `npm run storybook:build` succeeded.

**Comment by fabien0102** [comment]
Deploy preview for *fabien0102-gatsby-starter* ready!

Built with commit a454c10c8e7ed4bb285b32709e9e69c32f7dc9f7

https://deploy-preview-96--fabien0102-gatsby-starter.netlify.com

**Comment by jamestharpe** [comment]
Found an issue when serving the storybook - next push will contain the fix.

**Comment by jamestharpe** [comment]
Anything else I can do for this PR?

**Comment by fabien0102** [comment]
Looks good!

**Pull request merged**
