### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by bensontrent**
Updated dependencies and removed `next` version numbers as these no longer exist to enable a successful `npm install`.

### CODE REVIEW

**Comment by fabien0102** [comment]
image

We may need to update the version of typescript also 😉 Thanks for your contribution 👍

**Comment by bensontrent** [comment]
I'm sorry I haven't done this in a while, I probably should have submitted this pull request on a branch.  Still attempting to squash the errors on my side.  I was able to update storybook and webpack, and add the missing peer dependencies with safer security-audit-passing versioning.

**Comment by fabien0102** [comment]
Deploy preview for *fabien0102-gatsby-starter* ready!

Built with commit afd7d83c5af106f34b913bad123a07e28958c7c2

https://deploy-preview-89--fabien0102-gatsby-starter.netlify.com

**Comment by fabien0102** [comment]
@bensontrent Don't worry, your repo (even on master) is still a branch from this perspective 😉 

Thanks for your contribution, just waiting that everything is green to be able to merge 💯

**Comment by fabien0102** [comment]
image

You have something strange on one snapshot 😉

**Comment by bensontrent** [comment]
I still have one test that needs to be corrected to satisfy the updated Jest package and node.  The  `"should throw an error on graphql error"` test has an `UnhandledPromiseRejectionWarning` warning from node and needs to be re-written. Perhaps someone could help out.

**Comment by bensontrent** [comment]
This PR is ready to go on my side. Let me know if you'd like this in a branch rebased on master.

**Comment by jspizziri** [comment]
@fabien0102 @bensontrent ,

Currently you can't create a new project from this starter because of these dependency issues. Is this going to make it in?

**Comment by bensontrent** [comment]
@fabien0102 I'm assuming you just haven't had the time to consider this PR or perhaps hesitant to check this in since I had to modify some of the tests. The tests were designed for an earlier version of Gatsby; I had to update them to conform with the output generated by the newer version of Gatsby and the updated dependencies.

@jspizziri you can try building from my working branch:

Run:
`git clone https://github.com/bensontrent/gatsby-starter.git && cd gatsby-starter && npm i`

However, I don't intend to keep that branch maintained, so make a note to yourself to merge in with the main fabien0102:master source down the road.

**Comment by fabien0102** [comment]
@bensontrent Thanks for your contribution 💯 If you are interested, I'm still looking for more contributor/maintainer. I don't really have time to maintain this project anymore (a lot of other sideproject and I don't use gatbsy currently).
Bref, if you want, I can give you more permissions on the project 😉

**Comment by bensontrent** [comment]
@fabien0102 sure I'm happy to help out. I'm not sure how much I will contribute either but at least I can keep an eye on it. Gatsby needs a good Typescript starter project and this is it.

**Comment by fabien0102** [comment]
@bensontrent Totally agreed with the needs of a good Typescript starter! You are now an official contributor 😃  Welcome to the team 🎉

**Pull request merged**
